Added method to remove tracer and the data associated (issue67)
LSSTDESC/sacc pull request #69
Opened 2021-11-03 21:46 UTC by carlosggarcia

Closes #67.

2021-11-04 12:39 UTC, carlosggarcia commented
I was thinking that it might be more useful and closer to `keep_selection` and `remove_selection`, if `remove_tracer` would actually be `remove_tracers` and I added another method `keep_tracers`

2022-02-24 14:17 UTC, joezuntz requested changes
Same comment as last PR - if you can tweak slightly to avoid assuming that there are two tracers then perfect.

2022-02-24 14:17 UTC, joezuntz commented on sacc/sacc.py
> +            if (name in trs[0]) or (name in trs[1]):
Same comment as other PR!

2022-02-24 15:41 UTC, carlosggarcia commented on sacc/sacc.py
> +            if (name in trs[0]) or (name in trs[1]):
Done!

2022-02-24 15:42 UTC, carlosggarcia commented
@joezuntz back to you. Thanks for reviewing! In the end, I've added `keep_tracers` and `remove_tracers`. It seems more versatile.

2022-02-24 17:16 UTC, joezuntz approved these changes

2022-02-24 17:16 UTC, merged

2022-02-24 17:16 UTC, joezuntz commented
Thanks!